
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.stockexchange.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.7
 * 2014-01-21T21:27:43.748+01:00
 * Generated source version: 2.3.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ExchangeServiceService",
                      portName = "ExchangeServicePort",
                      targetNamespace = "http://service.stockexchange.ce.jku.at/",
                      wsdlLocation = "http://140.78.73.67:8080/CEStockExchangeWS/services/exchangeservice?wsdl",
                      endpointInterface = "at.jku.ce.stockexchange.service.ExchangeService")
                      
public class ExchangeServiceImpl implements ExchangeService {

    private static final Logger LOG = Logger.getLogger(ExchangeServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#buyStock(java.lang.String  arg0 ,)int  arg1 )*
     */
    public at.jku.ce.stockexchange.service.Exchange buyStock(java.lang.String arg0,int arg1) { 
        LOG.info("Executing operation buyStock");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        	
        	//TODO implement my logic here
        	
        	// TODO DB Zugriff hier asdf
        	
            at.jku.ce.stockexchange.service.Exchange _return = new at.jku.ce.stockexchange.service.Exchange();
            _return.setExchangeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-21T21:27:43.810+01:00"));
            _return.setExecution(-39703007);
            _return.setOrder(-838349336);
            _return.setSale(true);
            at.jku.ce.stockexchange.service.Stock _returnStock = new at.jku.ce.stockexchange.service.Stock();
            _returnStock.setAvailability(-1477425329);
            _returnStock.setCurrency("Currency-1505351060");
            _returnStock.setIsin("Isin1870069911");
            _returnStock.setName("Name1833041292");
            _returnStock.setPrice(Double.valueOf(0.7081955323401781));
            _returnStock.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-21T21:27:43.828+01:00"));
            _return.setStock(_returnStock);
            at.jku.ce.stockexchange.service.StockExchange _returnStockExchange = new at.jku.ce.stockexchange.service.StockExchange();
            _returnStockExchange.setMic("Mic-2025196356");
            _returnStockExchange.setName("Name1952913290");
            _return.setStockExchange(_returnStockExchange);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#getExchanges(*
     */
    public java.util.List<at.jku.ce.stockexchange.service.Exchange> getExchanges() { 
        LOG.info("Executing operation getExchanges");
        try {
            java.util.List<at.jku.ce.stockexchange.service.Exchange> _return = new java.util.ArrayList<at.jku.ce.stockexchange.service.Exchange>();
            at.jku.ce.stockexchange.service.Exchange _returnVal1 = new at.jku.ce.stockexchange.service.Exchange();
            _returnVal1.setExchangeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-21T21:27:43.831+01:00"));
            _returnVal1.setExecution(-43779389);
            _returnVal1.setOrder(313553252);
            _returnVal1.setSale(true);
            at.jku.ce.stockexchange.service.Stock _returnVal1Stock = new at.jku.ce.stockexchange.service.Stock();
            _returnVal1Stock.setAvailability(-953838796);
            _returnVal1Stock.setCurrency("Currency-1814435766");
            _returnVal1Stock.setIsin("Isin-1162587095");
            _returnVal1Stock.setName("Name254159275");
            _returnVal1Stock.setPrice(Double.valueOf(0.6175586960247137));
            _returnVal1Stock.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-21T21:27:43.832+01:00"));
            _returnVal1.setStock(_returnVal1Stock);
            at.jku.ce.stockexchange.service.StockExchange _returnVal1StockExchange = new at.jku.ce.stockexchange.service.StockExchange();
            _returnVal1StockExchange.setMic("Mic1346567416");
            _returnVal1StockExchange.setName("Name-361961920");
            _returnVal1.setStockExchange(_returnVal1StockExchange);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#sellStock(java.lang.String  arg0 ,)int  arg1 )*
     */
    public void sellStock(java.lang.String arg0,int arg1) { 
        LOG.info("Executing operation sellStock");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#getStock(java.lang.String  arg0 )*
     */
    public at.jku.ce.stockexchange.service.Stock getStock(java.lang.String arg0) { 
        LOG.info("Executing operation getStock");
        System.out.println(arg0);
        try {
            at.jku.ce.stockexchange.service.Stock _return = new at.jku.ce.stockexchange.service.Stock();
            _return.setAvailability(-47594438);
            _return.setCurrency("Currency258724882");
            _return.setIsin("Isin588470287");
            _return.setName("Name-570878588");
            _return.setPrice(Double.valueOf(0.956859506377862));
            _return.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-21T21:27:43.834+01:00"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#getTradedStocks(*
     */
    public java.util.List<at.jku.ce.stockexchange.service.Stock> getTradedStocks() { 
        LOG.info("Executing operation getTradedStocks");
        try {
            java.util.List<at.jku.ce.stockexchange.service.Stock> _return = new java.util.ArrayList<at.jku.ce.stockexchange.service.Stock>();
            at.jku.ce.stockexchange.service.Stock _returnVal1 = new at.jku.ce.stockexchange.service.Stock();
            _returnVal1.setAvailability(333189205);
            _returnVal1.setCurrency("Currency-1416840852");
            _returnVal1.setIsin("Isin-662445725");
            _returnVal1.setName("Name620321799");
            _returnVal1.setPrice(Double.valueOf(0.2762895599877755));
            _returnVal1.setPublication(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-01-21T21:27:43.835+01:00"));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.stockexchange.service.ExchangeService#reset(*
     */
    public void reset() { 
        LOG.info("Executing operation reset");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
